### ISSUE TITLE
Evernote: Titles with quotation marks are imported as Untitled Note

### ISSUE THREAD

**Issue by OM1720** [obsidianmd/obsidian-importer#185]
If evernote-notes title surrounded by quotation marks in obsidian-note doesn't have title (Untitled Note).

**Comment by russp41** [comment]
Every Evernote notebook I've imported so far via ENEX file into Obsidian has some notes imported as Untitled. Usually it's only two or three, but today I imported a notebook with 692 notes, and 13 of them were imported as Untitled. These notes do not have quotation marks in the title. In this particular case, the note titles have a text code in square brackets "[" "]". The vast majority of these imported correctly into Obsidian but with the "[" "]" stripped out since Obsidian can't use those characters in the file name. Another small notebook of 10 notes imported with one note left as Untitled. That note had no punctuation or special characters in the title.

**Comment by akosbalasko** [comment]
Hi @russp41 ,
Unfortunately I cannot reproduce the issue, importing notes with quotation marks and brackets works well. And if I check the code, "Untitled" is generated as note name in only one case: if there is no title found in the enex file. 
Could you pls share me the enex file which contains a note that is converted to Untitled note?  
Thanks for you help!
