### ISSUE TITLE
[OneNote] Sign in error: typeerror cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by fjacquet** [obsidianmd/obsidian-importer#233]
After a correct login to my  M635 account, I face a TypeError blocking the enumeration of my Notebook  : 
```javascript 
typeerror cannot read properties of undefined (reading 'value')
```
![Capture d’écran 2024-04-09 à 20 21 53](https://github.com/obsidianmd/obsidian-importer/assets/7874189/afb7fc32-2d4d-47b0-8246-7cd697113392)

I don't have the skills to debug but I am happy to assist if needed. Did not find any similar issue in bounty.
Occurs on Mac and Win11

**Comment by enoola** [comment]
Hello I experiment the same with macbook m3 (16-inch, Nov 2023) , I have HAR capture and console logs I can provide. HAR is quite sensitive so let me know.
Sonoma 14.4.1 (up to date when writing this)
tested with edge,chrome,safari
deactivated ublock, and few unrelated plugin, reduced tracking prevention from strict to balanced
nothing did it

**Comment by amyers1616** [comment]
Can confirm error on Linux and Windows 10 too.

**Comment by robbbyn** [comment]
Same error for me on Firefox on Windows 10. Auth worked initially, however the Importer did not import properly; subsequent attempts to auth again then failed afterwards.

**Comment by GregHib** [comment]
Console log below, it's microsoft returning 429 (too many requests) after 5+ sign-ins. Importer doesn't seem to store and reuse the login token between imports even when pressing the "back" button after an import.

OneNotes api is throttled to 5 concurrent requests per app per user: https://learn.microsoft.com/en-us/graph/throttling-limits#onenote-service-limits

```
Failed to load resource: the server responded with a status of 429 ()
An error has occurred while fetching an resource: 
{
    "error": {
        "code": "20166",
        "message": "The app has issued too many requests on behalf of this user in a short time period.",
        "innerError": {
            "date": "2024-04-19T14:39:21",
            "request-id": "c3bc1789-bd97-485b-8dfe-3bf943047d2e",
            "client-request-id": "c3bc1789-bd97-485b-8dfe-3bf943047d2e"
        }
    }
}
An error occurred while we were trying to sign you in. Error details:  TypeError: Cannot read properties of undefined (reading 'value')
    at Mr.showSectionPickerUI (plugin:obsidian-importer:214:1374)
    at async Mr.authenticateUser (plugin:obsidian-importer:214:716)
```

**Comment by GregHib** [comment]
This bug would be that the error isn't properly displayed to the user. The actual solution would be #117

**Comment by HavenAdventures** [comment]
I'm not even getting one import to work before getting this error. My issue does not to be related to a timeout

**Comment by enoola** [comment]
> I'm not even getting one import to work before getting this error. My issue does not to be related to a timeout
I have the same output as @fjacquet , but without a glance at it working at all.
so the error
```
{"An error has occurred while fetching an resource:",{"error":{"code":"10008","message":"One or more of the document libraries on the user or group's OneDrive contains more than 5,000 OneNote items (notebooks, sections, section groups) and cannot be queried using the API. Please make sure that none of the user or group's document libraries contains more than 5,000 OneNote items. Browse to this page for more information: https://blogs.msdn.microsoft.com/onenotedev/2016/09/11/onenote-api-calls-fail-with-a-large-number-of-items-in-a-sharepoint-document-library/","innerError":{"date":"2024-04-26T00:11:47","request-id":"81b24599-d7a6-4ed7-b569-036d3dfb4826","client-request-id":"81b24599-d7a6-4ed7-b569-036d3dfb4826"}}}
```
to note : " the user or group's OneDrive contains more than 5,000 OneNote items .. cannot be queried ..."
=> https://blogs.msdn.microsoft.com/onenotedev/2016/09/11/onenote-api-calls-fail-with-a-large-number-of-items-in-a-sharepoint-document-library

In essence I agree with @GregHib , pointing out the limitation and a link to the above would be a solution AFAIK.
now I need to find or make something to split my object across multiple users :D

**Comment by xinzihou** [comment]
Same issue on Chrome and MacOS 10.13. I've imported twice successfully and from the third time this error occurred. I've been logged in my OneNote account all time.

**Comment by RavHilton** [comment]
Same issue here when authing through an Opera browser - some data imports, then it consistently fails.  Retrying just leaves me with this error and no further hope of importing...

**Comment by RavHilton** [comment]
Importer just updated to 1.6.4 and the same error remains...

**Comment by marc-signer** [comment]
I'm experiencing the same problem and can confirm that my console also says it is due to a 429 (Too Many Requests) error.
It occured each time after the import of a rather large notebook that failed halfway through (also because of too many requests). After waiting a day and trying again, the login worked but I got to the same point again after trying to import a larger notebook.
I'm on Windows / Chrome.

Is there a solution or a workaround to this problem? Doesn't seem like there's a whole lot one can do as an end user and it's kinda frustrating.

**Comment by varju** [comment]
> Is there a solution or a workaround to this problem? Doesn't seem like there's a whole lot one can do as an end user and it's kinda frustrating.

In my case I split my notebook into smaller sections and imported the sections one at a time, with a break each time I started getting 429 errors.

**Comment by marc-signer** [comment]
@varju Oh alright, tysm for the tip! Have you found out what roughly the maximum amount of pages is that can be handled without throwing an error? And by splitting do you mean just split the selection of the import or literally split the notebook?

**Comment by varju** [comment]
> @varju Oh alright, tysm for the tip! Have you found out what roughly the maximum amount of pages is that can be handled without throwing an error? And by splitting do you mean just split the selection of the import or literally split the notebook?

In my case I only had one large notebook with several large sections. I rearranged my sections into chunks of about 50 notes each. I think I was able to import 2 or 3 of these sections before it started rate limiting again. Larger than 50 and the initial section query tended to time out, aborting the import with a different hidden error.

Problems were compounded for me because it turns out many of my notes had never synced to the cloud, causing 404s during import. I had to manually force syncing on each note, likely consuming more of my quota.

**Comment by philllie** [comment]
i also have this problem, meaning I cannot import my notes and therefore not use and switch to Obsidian.
Wouldnt it be in the interest of Obsidian too, to solve this problem after nearly 3/4 of a year???

**Comment by tgrosinger** [comment]
Unfortunately, there is nothing we can do about the Microsoft limitations on how fast we can import notes through the API, but we can at least make the messaging and retries a bit better.

I've got some changes on a branch that anyone is welcome to try out and report back how it goes:
- Allow remembering your signed in account
- Renew access token if imports take longer than the 1 hour lifetime of the token
- Add option to skip previously imported notes (only considers notes imported since this update)
- Add improved error messaging when rate limiting is occurring.

Please give it a try and let me know if you encounter any issues. You can try it by replacing the main.js in `your vault/.obsidian/plugins/obsidian-importer` with this one: [main.zip](https://github.com/user-attachments/files/17652134/main.zip)

**Comment by RazgovovEvgen22** [comment]
I started testing while everything is working.

**Comment by tgrosinger** [comment]
Can you please elaborate on what you mean by "authorization fails"? Is that after hitting the rate limit? Does it fail every time?

**Comment by tgrosinger** [comment]
Oh excellent, thank you for testing!

**Comment by RazgovovEvgen22** [comment]
There are errors "429", also noticed the text, not all was copied, in several notes, but I think there is no point in debugging and testing.

**Comment by RazgovovEvgen22** [comment]
Duplicates of notes and files are being created due to my mistake. I ran the import at home and at work, on different computers. If I had used just one, I think it would have been fine. I'll test it later this week. I have a lot of notes and files attached to them, approximately 7,000 files and 900 notes (rough estimate). By the end of the import, there were 16,000 files with duplicates. I didn't count the notes, and not all notes were duplicated, but some were duplicated multiple times. 

The script is good anyway, despite my mistake.)))
Thank you for the development and the time spent.

**Comment by tgrosinger** [comment]
Thanks very much for continuing to test, this is very helpful. Yeah, as you discovered the tracking of which files were imported is local to the instance of Obsidian because I didn't want to add an indicator into the files themselves.

I'll go ahead and release this update, and if there are specific issues that come up afterwards we can track them in a new issue.

**Comment by tgrosinger** [comment]
Closing with [1.6.11](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.6.11)

**Comment by untotren** [comment]
> Closing with [1.6.11](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.6.11)

Not sure why this is closed, a year later and this very basic functionality is still broken. Hard to take yall serious when such a simple thing doesn't function. Is this the norm for this product?
