### ISSUE TITLE
Failed to load plugin on Obsidian desktop app

### ISSUE THREAD

**Issue by aaditkamat** [obsidianmd/obsidian-importer#271]
The specs for my laptop: MacBook Pro 13-inch, M1 2020 model (16GB memory)

I'm currently running v1.6.3 of the Obsidian Desktop App which I installed on my system using Homebrew.

The issue I'm facing is that I'm unable to load the plugin on my app, which I wish to use to import my Apple Notes to Obsidian.

Here is the screenshot of the message that pops up when I try to load the plugin:

<img width="987" alt="Obsidian Importer" src="https://github.com/obsidianmd/obsidian-importer/assets/30969577/9d8e8744-c57b-4b94-b520-78b71805aa75">

**Comment by kepano** [comment]
Which installer version are you using?

https://help.obsidian.md/Getting+started/Update+Obsidian

**Comment by aaditkamat** [comment]
> Which installer version are you using?
> 
> [help.obsidian.md/Getting+started/Update+Obsidian](https://help.obsidian.md/Getting+started/Update+Obsidian)

I'm seeing it as the latest version v1.6.3 as I have mentioned.

**Comment by kepano** [comment]
To clarify there is is a difference between the installer version and the app version. But you might have the latest for both. Have you tried installing the app via the installer on the [download](**url**) page (rather than Homebrew)?

<img width="212" alt="Screenshot 2024-06-15 at 12 26 53" src="https://github.com/obsidianmd/obsidian-importer/assets/10565871/31e7bd2c-0604-4916-b481-134b6b1ec0aa">

**Comment by aaditkamat** [comment]
The issue persists despite installing from the website latest
<img width="975" alt="Screenshot 2024-06-16 at 10 40 55 PM" src="https://github.com/obsidianmd/obsidian-importer/assets/30969577/8803d42e-2204-49ff-bd82-14ad98360d11">
