### ISSUE TITLE
OneNote Tables are not imported correctly

### ISSUE THREAD

**Issue by boksir** [obsidianmd/obsidian-importer#302]
I tried importing my documents from OneNote. I use tables extensively, and the table import doesn't seem to work well. Attaching screenshots of the OneNote table and the imported note in Obsidian

<img width="604" alt="image" src="https://github.com/user-attachments/assets/96eea8e7-7345-4ce9-932c-57e05a9d14b8">
OneNote Table

<img width="1131" alt="image" src="https://github.com/user-attachments/assets/0c27d71c-4663-44a9-a75e-4783b71635b0">
Obsidian Table

Only about 1% of the tables imported correctly
Thanks for your help.

**Comment by tgrosinger** [comment]
Hello,
It looks like this issue is probably caused by the htmlToMarkdown conversion that is performed in Obsidian by [Turndown](https://github.com/mixmark-io/turndown). Markdown does not natively support newlines or lists in a table, so the only way to do that is to leave the HTML inside the table cell if there are elements not supported by Markdown. This is not currently supported by the Importer plugin but may be something that could be added in the future. Obsidian does already support rendering tables with HTML in the cells.
