### ISSUE TITLE
Google Keep: unnecessary alias

### ISSUE THREAD

**Issue by NomarCub** [obsidianmd/obsidian-importer#65]
Aliases should only be used when the title would be an invalid file name, otherwise it's just duplicated information. Now every note with a title has one.
Notes that don't have a title in Keep get a date title, but no alias, which is also weird.

**Comment by lishid** [comment]
@daledesilva I am not sure I understand the purpose of using keepJson.title.split('\n') for aliases. Can notes have multiple titles?

**Comment by NomarCub** [comment]
Notes can have titles that are more than one line long, but I only noticed that accidentally.
The data then looks like this: `"title": "line one\nline two",`. It can even have trailing newlines.

**Comment by lishid** [comment]
For `"line one\nline two"`, what does the filename become?

**Comment by NomarCub** [comment]
With 1.1.0, it's `line one_line two`
The alias becomes `line one line two`

**Comment by lishid** [comment]
Hmm ok, so we should probably ignore the title field altogether? What do you think @daledesilva?

**Comment by NomarCub** [comment]
Definitely don't ignore the title, at least for file names. Notes can even be only a title. I don't think many people use multi line titles, you'd have to know and press shit enter, or a normal enter would take you to the note content when you input it. (Or you can just copy text there that has more lines.)
I think it's fine as is, collapsing multi line titles with a single space, and keeping the file name with underscores.

**Comment by lishid** [comment]
The file name is created from what Keep exports as file names in the zip. If it's always some combination of flattened "title" field then it would make sense to ignore.

**Comment by NomarCub** [comment]
I think that's what it is, yes, and if there's no title, it's the date instead. But I would not ignore it, unless you have some better mechanism for creating a file name or title. It makes a lot of sense to me, to have the OS friendly file name, and if it differs from the original, have an alias field with the original title with special characters if there were any.

**Comment by lishid** [comment]
Ok so it makes sense to alias to `line one` and `line two`, which is the current behavior.

**Comment by daledesilva** [comment]
Agree with all of this. That was my thinking when I did it.

To reiterate

- Notes can often just be a title.
- The obsidian note name is just what keep exported as filename so it's already sanitised.
- Because the original title can have any character or even line breaks, the filename can be different, so the original title is added as an alias.
- To prevent multi line aliases, new line chars are replaced with spaces.

Note, I considered checking whether the title matched the filename and only adding the alias if different, but I decided to just keep it simple and consistent for every note.
